# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aegis.romhackhispano.org" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Aegis Traducciones
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "AegisTrad es el templo donde publico traducciones de videojuegos que me encantan y que lamentablemente no llegaron a verse en español. "

  # Header and footer text
  header_text: >
     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

     <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  header_text_feature_image:
  footer_text: >
     Este sitio está alojado en <a href="http://www.romhackhispano.org">Romhack Hispano</a> y funciona bajo <a href="http://jekyllrb.com">Jekyll</a> con el tema <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> modificado por TheFireRed.
  # El contenido mostrado aquí es copyright de sus respectivos autores originales. Aegis Traducciones condena el empleo de <i>software</i> obtenido de manera ilegal y no se hace responsable de los efectos causados por el mal uso de las herramientas publicadas en este sitio. Consulta la <a href="https://help.disqus.com/customer/portal/articles/466259-privacy-policy">política de privacidad</a>. Aegis Traducciones es posible gracias a la inestimable colaboración de la escena hispana.
	
  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "TheFireRed"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "TheFireRed"
  wordpress:
  youtube: "TheFireRed"

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
