# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aegis.romhackhispano.org" # the base hostname & protocol for your site
title: Aegis Traducciones
description: "AegisTrad es el templo donde publico traducciones de videojuegos que me encantan y que lamentablemente no llegaron a verse en español. "

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Aegis Traducciones
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "AegisTrad es el templo donde publico traducciones de videojuegos que me encantan y que lamentablemente no llegaron a verse en español. "

  # Header and footer text
  # header_text: >
  #   <p>La página está en construcción; o mejor dicho, de mudanzas. Es posible que falten cosas, que los enlaces estén más rotos que un jarrón de Ming en Worms Armageddon o que las páginas no tengan gusto por los colores y tipografías. En los siguientes enlaces encontrarás enlaces alternativos al contenido que se expondrá aquí. <a href="http://www.romhacking.net/community/2570/">Romhacking.net</a> <a href="https://twitter.com/TheFireRed">@TheFireRed</a> </p>
  # header_text_feature_image:
  footer_text: >
     Este sitio está alojado en <a href="http://www.romhackhispano.org">Romhack Hispano</a> y funciona bajo <a href="http://jekyllrb.com">Jekyll</a> en <a href="http://github.com">GitHub</a>.
  # El contenido mostrado aquí es copyright de sus respectivos autores originales. Aegis Traducciones condena el empleo de <i>software</i> obtenido de manera ilegal y no se hace responsable de los efectos causados por el mal uso de las herramientas publicadas en este sitio. Consulta la <a href="https://help.disqus.com/customer/portal/articles/466259-privacy-policy">política de privacidad</a>. Aegis Traducciones es posible gracias a la inestimable colaboración de la escena hispana.  con el tema <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> modificado por TheFireRed.
  # Icons
  rss: true
  email_address:
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "TheFireRed"
  google_plus:
  instagram:
  linkedin:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  twitter: "TheFireRed"
  wordpress:
  youtube: "TheFireRed"

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: aegistrad
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Sígueme en"
  str_rss_follow: "RSS"
  str_email: "Email"
  str_next: "Siguiente"
  str_prev: "Anterior"
  str_continue_reading: "Seguir leyendo"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
